// SPDX-License-Identifier: UNLICENSED

pragma solidity ^0.8.0;

import { IOwnableInternal } from '@solidstate/contracts/access/ownable/IOwnableInternal.sol';

interface IShardVaultInternal is IOwnableInternal {
    /**
     * @notice thrown when the deposit amount is not a multiple of shardSize
     */
    error ShardVault__InvalidDepositAmount();

    /**
     * @notice thrown when the maximum capital has been reached or vault has invested
     */
    error ShardVault__DepositForbidden();

    /**
     * @notice thrown when the withdraw amount exceeds the owed shards to the sender
     */
    error ShardVault__InsufficientShards();

    /**
     * @notice thrown when the maximum capital has been reached or vault has invested
     */
    error ShardVault__WithdrawalForbidden();

    /**
     * @notice thrown when function called by non-protocol owner
     */
    error ShardVault__OnlyProtocolOwner();

    /**
     * @notice thrown when function called by non-shard owner
     */
    error ShardVault__OnlyShardOwner();

    /**
     * @notice thrown when a tokenId is not generated by current vault address
     */
    error ShardVault__VaultTokenIdMismatch();
}
